select 
    A.CD_TIPOCLAS,
    A.CD_CLASSIFICACAO,       
    A.DS_CLASSIFICACAO,
    TO_CHAR (A.CD_PEDIDO),
    A.DT_CADASTRO,
    TO_CHAR(A.CD_CLIENTE),
    TO_CHAR(A.CD_REPRESENTANT),   
    B.TP_SITUACAO,
    B.CD_MOTIVOBLOQ,
    C.DS_MOTIVO
        
FROM 
  
   VR_PED_PEDIDOCLAS A
INNER JOIN
    VR_PED_PEDIDOI B
ON A.CD_PEDIDO = B.CD_PEDIDO
INNER JOIN 
    VR_PED_MOTIVOBLOQ C
ON B.CD_MOTIVOBLOQ = C.CD_MOTIVO
WHERE
    B.TP_SITUACAO IN ('5')
GROUP BY A.CD_TIPOCLAS,
    A.CD_CLASSIFICACAO,       
    A.DS_CLASSIFICACAO,
    A.CD_PEDIDO,
    A.DT_CADASTRO,
    A.CD_CLIENTE,
    A.CD_REPRESENTANT,   
    B.TP_SITUACAO,
    B.CD_MOTIVOBLOQ,
    C.DS_MOTIVO
ORDER BY C.DS_MOTIVO
